### PR TITLE
feat: ping pong command

### PR DESCRIPTION
**Pull request by heyk1n**
* This pull request contains command handler, manifest build and more.

### CODE REVIEW

**Review by aureziaa — COMMENTED** [review]
```typescript
import { isChatInput } from "./utils/command.ts";
import { stringToBoolean } from "./utils/convert.ts";
import { isCommand, isPing } from "./utils/interaction.ts";
```

Kalo gini kayak kebanyakan line ga si?

**Comment by heyk1n** [comment]
> ```ts
> import { isChatInput } from "./utils/command.ts";
> import { stringToBoolean } from "./utils/convert.ts";
> import { isCommand, isPing } from "./utils/interaction.ts";
> ```
> 
> Kalo gini kayak kebanyakan line ga si?

maksudnya?

**Comment by aureziaa** [comment]
> > ```ts
> > import { isChatInput } from "./utils/command.ts";
> > import { stringToBoolean } from "./utils/convert.ts";
> > import { isCommand, isPing } from "./utils/interaction.ts";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Kalo gini kayak kebanyakan line ga si?
> 
> maksudnya?

kalo import dari satu folder satu per satu kayak gitu kayak terlalu numpuk, saran saya teh bikin satu file khusus di folder `utils` untuk re-export semua file disana \:3

**Comment by heyk1n** [comment]
oh, semacam `utils/mod.ts` ya?

**Comment by aureziaa** [comment]
> oh, semacam `utils/mod.ts` ya?

yup

**Comment by heyk1n** [comment]
> > oh, semacam `utils/mod.ts` ya?
> 
> yup

instruction clear, gw ubah nanti

**Review by aureziaa — CHANGES_REQUESTED** [review]
create re-export file for `utils` folder

**Review by aureziaa — APPROVED** [review]

**Pull request merged**
